import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeIcon from "@/components/atoms/icons/HomeIcon";
import AboutIcon from "@/components/atoms/icons/AboutIcon";
import Link from "next/link";
import { NextUIProvider } from "@nextui-org/react";
import NavBar from "@/components/templats/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
        <div className="flex bg-sky-950 flex-col">
          <div>
            <NavBar />
          </div>
          <div>
            {children}
          </div>
        </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
